In [1]:
import numpy

In [2]:
def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    crossover_point = numpy.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        parent1_idx = k%parents.shape[0]
        parent2_idx = (k+1)%parents.shape[0]
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

In [3]:
def cal_pop_fitness(equation_inputs, pop):
    fitness = numpy.sum(pop*equation_inputs, axis=1)
    return fitness

def select_mating_pool(pop, fitness, num_parents):
    parents = numpy.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

def mutation(offspring_crossover):
    for idx in range(offspring_crossover.shape[0]):
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

In [4]:
def main():
    equation_inputs = [4,-2,3.5,5,-11,-4.7]

    num_weights = 6
    sol_per_pop = 8
    num_parents_mating = 4
    
    pop_size = (sol_per_pop,num_weights)
    new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
    print(new_population)
    
    num_generations = 5
    for generation in range(num_generations):
        print("Generation : ", generation)
        fitness = cal_pop_fitness(equation_inputs, new_population)
        parents = select_mating_pool(new_population, fitness, num_parents_mating)
        offspring_crossover = crossover(parents, offspring_size=(pop_size[0]-parents.shape[0], num_weights))
        offspring_mutation = mutation(offspring_crossover)
        new_population[0:parents.shape[0], :] = parents
        new_population[parents.shape[0]:, :] = offspring_mutation
    
        print("Best result : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))
    
    fitness = cal_pop_fitness(equation_inputs, new_population)
    best_match_idx = numpy.where(fitness == numpy.max(fitness))
    
    print("Best solution : ", new_population[best_match_idx, :])
    print("Best solution fitness : ", fitness[best_match_idx])

In [5]:
main()

[[ 2.82565727 -1.57646978  3.67858561 -0.17802085  3.79016739 -1.59551653]
 [ 2.48427266 -0.2364029  -3.35710957  3.56387353 -3.28008916  2.75123124]
 [ 0.56181447 -0.28768369  1.91025678 -1.4129046   1.75715278  2.87014828]
 [-1.60825052 -1.4044001  -2.05812969  2.76478122 -3.25476148 -1.29336717]
 [ 2.19207631  1.86651071  1.60663882 -2.98470793  3.14801988  0.58991026]
 [ 2.6929956   0.27131767 -3.26856521  2.01442493 -2.53485449 -0.6929527 ]
 [-0.08639606  1.97639133 -3.00365592 -0.06736582 -0.08926731  1.89921219]
 [ 2.25661496 -0.46567203 -1.64145681  0.71810142 -1.94320573  1.03687527]]
Generation :  0
Best result :  53.756005921378986
Generation :  1
Best result :  57.43659674049949
Generation :  2
Best result :  63.043104820172545
Generation :  3
Best result :  73.36605292972514
Generation :  4
Best result :  73.36605292972514
Best solution :  [[[ 2.25661496 -0.46567203 -1.64145681  2.76478122 -4.47732873
   -1.29336717]]]
Best solution fitness :  [73.36605293]
